[package]
name = "MumenController"
version = "0.1.0"
authors = ["nulvox <38874956+nulvox@users.noreply.github.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "MumenController"
test = false
bench = false

[dependencies]
panic-halt = "0.2.0"
ufmt = "0.1.0"
nb = "0.1.2"
embedded-hal = "0.2.3"
# usb-device = "0.2.9"
# usbd-human-interface-device = "0.4.3"

[dependencies.usbd-human-interface-device]
version = "0.4.3"
path = "../usbd-human-interface-device"

[dependencies.avr-device]
version = "0.5.2"
features = ["atmega32u4"]

# [dependencies.usbd-human-interface-device]
# git = "https://github.com/nulvox/usbd-human-interface-device"
# rev = "afe86e9a42bb1cee1985c2543380b67c7d571d09"

[dependencies.arduino-hal]
git = "https://github.com/rahix/avr-hal"
rev = "190f2c3cb8d29e10f71119352b912369dc5a1fb7"
features = ["sparkfun-promicro"]

# Configure the build for minimal size - AVRs have very little program memory
[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "s"

[build]
rustflags = ["--cfg", "portable_atomic_no_outline_atomics"]
