[package]
authors = ["nulvox", "heethar"]
name = "mumencontroller"
version = "0.1.0"
edition = "2021"

[dependencies]
panic-halt = "0.2.0"
ufmt = "0.1.0"
nb = "0.1.2"
embedded-hal = "0.2.3"
usb-device = "0.2.3"
usbd-hid-device = "0.1.0"

[dependencies.arduino-hal]
features = ["arduino-leonardo"]

[profile]

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = "s"
