[build]
target = "avr-specs/avr-atmega32u4.json"
# target = "avr-specs/avr-atmega32u4-softatomic.json"
# rustflags = "--emit=obj"

[target.'cfg(target_arch = "avr")']
runner = "ravedude leonardo"

[unstable]
build-std = ["core"]
build-std-features = [
    "compiler-builtins-mangled-names",
    "panic_immediate_abort",
]
